[package]
name = "piggybank"
version = "0.5.2"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.39.6"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.6"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
