[package]
name = "piggybank"
version = "0.5.3"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.42.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.42.0"
