[package]
name = "piggybank-meta"
version = "0.5.1"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2021"
publish = false

[dependencies.piggybank]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
